
LDFLAGS =         -lpthread -lcuda 
CPPFLAGS = -Werror -Wall -I../src -I../../PsimagLite/src \
	     -I /usr/include/cuda
CXX = g++ -g3 -DNDEBUG

all: simpleQuery
	
clean:
	rm -f core* $(EXENAME) *.o *.ii *.tt


######## End of Makefile ########

