
LDFLAGS =         -lpthread -lcuda 
CPPFLAGS = -Werror -Wall -I../src -I../../PsimagLite/src \
  -I/opt/NVIDIA_GPU_Computing_SDK/C/common/inc/ -I /opt/cuda/include/
CXX = g++ -g3 -DNDEBUG


	
clean:
	rm -f core* $(EXENAME) *.o *.ii *.tt


######## End of Makefile ########

